name: Deploy to heroku
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       
      - name: checkout backend
        run: |
          git clone https://github.com/photongupta/todoServer.git backend
          cd backend
          npm install
          npm test

      - name: Create build
        run: |
          pwd
          git clone https://github.com/photongupta/todoApp.git frontend
          cd frontend
          npm install
          npm test
          npm run build
          mv build/ ../backend/public/.
          cd ..

      - name: push to repository
        env:
          GIT_SSH_COMMAND: 'ssh -o StrictHostKeyChecking=no'
        run: |
          eval "$(ssh-agent -s)"
          ssh-add - <<< ${{secrets.DEPLOY_KEY }}
          git clone git@github.com:photongupta/learn_github_actions.git build
          cd build
          rm -rf *
          mv ../backend/* .
          git add .
          git config --global user.name "photongupta"
          git config --global user.email  "58028408+photongupta@users.noreply.github.com"
          git commit -m "Backend: $(../backend && git log -n 1 --format=%B)"
          git push -u origin main




          
   