name: Deploy to heroku
on: push

jobs:
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: photonogupta/todoApp
          token: ${{ secrets.my_toke }}
          path: todoApp
      