name: Deploy to heroku
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to frontend
        env:
         DEFAULT_BRANCH: master
        uses: actions/checkout@v2
        with:
          repository: photongupta/todoApp
          # token: ${{ secrets.my_token }}
          path: todoApp
       