name: Deploy to heroku
on: push

jobs:
  deploy to heroku:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to frontend
        uses: actions/checkout@v2
        with:
          repository: photonogupta/todoApp
          token: ${{ secrets.my_toke }}
          path: todoApp
   